"""added sub frequency

Revision ID: 9507395549d8
Revises: d16313ce80f2
Create Date: 2024-04-15 13:22:27.659485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9507395549d8'
down_revision = 'd16313ce80f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subscriptions', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
